version: x.x.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: dnlib.sln
  parallel: true
  verbosity: normal
before_package:
- cmd: msbuild /m /p:Configuration=Release /t:Pack dnlib.sln
artifacts:
- path: src\bin\Release\*.*nupkg
  name: dnlib NuGet Packages
notifications:
- provider: Email
  to:
  - de4dot@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  on:
    APPVEYOR_REPO_TAG: true
  api_key:
    secure: en/ChGrnyp08i9CgI/8WXLKhl0OHCpPsuBSRv9wt286kvKlI9P4732egbzq+ycfx
